### ISSUE TITLE
[BUG] RuntimeError: mat1 and mat2 shapes cannot be multiplied (50000x14 and 23x200) after loading the model

### ISSUE THREAD

**Issue by IantheChan** [takuseno/d3rlpy#131]
When  I try to use mopo.py after loading the pretrained dynamics to reproduce the results, I got this error. The full error message is shown below.
```
Epoch 1/500:   0%|                                     | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/v-litingchen/d3rlpy/reproductions/offline/mopo.py", line 90, in <module>
    main()
  File "/home/v-litingchen/d3rlpy/reproductions/offline/mopo.py", line 77, in main
    mopo.fit(dataset.episodes,
  File "/home/v-litingchen/d3rlpy/d3rlpy/base.py", line 405, in fit
    results = list(
  File "/home/v-litingchen/d3rlpy/d3rlpy/base.py", line 609, in fitter
    new_transitions = self.generate_new_data(
  File "/home/v-litingchen/d3rlpy/d3rlpy/algos/utility.py", line 37, in generate_new_data
    pred = self._dynamics.predict(observations, actions, True)
  File "/home/v-litingchen/d3rlpy/d3rlpy/dynamics/base.py", line 70, in predict
    observations, rewards, variances = self._impl.predict(
  File "/home/v-litingchen/d3rlpy/d3rlpy/torch_utility.py", line 309, in wrapper
    return f(self, *args, **kwargs)
  File "/home/v-litingchen/d3rlpy/d3rlpy/torch_utility.py", line 299, in wrapper
    return f(self, *tensors, **kwargs)
  File "/home/v-litingchen/d3rlpy/d3rlpy/dynamics/torch/base.py", line 54, in predict
    observation, reward, variance = self._predict(x, action, indices)
  File "/home/v-litingchen/d3rlpy/d3rlpy/dynamics/torch/probabilistic_ensemble_dynamics_impl.py", line 98, in _predict
    return self._dynamics.predict_with_variance(
  File "/home/v-litingchen/d3rlpy/d3rlpy/models/torch/dynamics.py", line 184, in predict_with_variance
    obs, rew, var = model.predict_with_variance(x, action)
  File "/home/v-litingchen/d3rlpy/d3rlpy/models/torch/dynamics.py", line 105, in predict_with_variance
    mu, logstd = self.compute_stats(x, action)
  File "/home/v-litingchen/d3rlpy/d3rlpy/models/torch/dynamics.py", line 86, in compute_stats
    h = self._encoder(x, action)
  File "/home/v-litingchen/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/v-litingchen/d3rlpy/d3rlpy/models/torch/encoders.py", line 403, in forward
    h = self._fc_encode(x)
  File "/home/v-litingchen/d3rlpy/d3rlpy/models/torch/encoders.py", line 330, in _fc_encode
    h = self._activation(fc(h))
  File "/home/v-litingchen/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/v-litingchen/anaconda3/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/v-litingchen/anaconda3/lib/python3.8/site-packages/torch/nn/functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (50000x14 and 23x200)
```
**To Reproduce**
I only deleted the codes from line 40-60 and add the following lines to mopo.py under reproductions/offline
```
    PATH='../../d3rlpy_logs/ProbabilisticEnsembleDynamics_20210831103936/model_30000.pt'
    PATH_json = '../../d3rlpy_logs/ProbabilisticEnsembleDynamics_20210831103936/params.json'
    dynamics =d3rlpy.dynamics.ProbabilisticEnsembleDynamics.from_json(PATH_json)
    dynamics.load_model(PATH)

```

**Comment by IantheChan** [comment]
I tried loading the models using another machine and this time there are no errors. I guess there are some problems with the running environment in my first machine, so I closed this issue.
