### ISSUE TITLE
What is the problem here?

### ISSUE THREAD

**Issue by hn2** [takuseno/d3rlpy#138]
Code used to work, suddenly stopped working:

Traceback (most recent call last):
  File "C:/QuantConnect/my-algos/drl-fx-d3rlpy/fit-online-fxcm-td3.py", line 298, in <module>
    main()
  File "C:/QuantConnect/my-algos/drl-fx-d3rlpy/fit-online-fxcm-td3.py", line 294, in main
    N_STEPS_PER_EPOCH, v_online_model_dir)
  File "C:/QuantConnect/my-algos/drl-fx-d3rlpy/fit-online-fxcm-td3.py", line 232, in train_online_model
    tensorboard_dir=online_model_dir if TENSORBOARD else None
  File "C:\Users\hanna\Anaconda3\lib\site-packages\d3rlpy\algos\base.py", line 292, in fit_online
    callback=callback,
  File "C:\Users\hanna\Anaconda3\lib\site-packages\d3rlpy\online\iterators.py", line 272, in train_single_env
    logger.save_model(total_step, algo)
  File "C:\Users\hanna\Anaconda3\lib\site-packages\d3rlpy\logger.py", line 155, in save_model
    algo.save_model(model_path)
  File "C:\Users\hanna\Anaconda3\lib\site-packages\d3rlpy\base.py", line 333, in save_model
    self._impl.save_model(fname)
  File "C:\Users\hanna\Anaconda3\lib\site-packages\d3rlpy\algos\torch\base.py", line 124, in save_model
    torch.save(get_state_dict(self), fname)
  File "C:\Users\hanna\Anaconda3\lib\site-packages\torch\serialization.py", line 373, in save
    return
  File "C:\Users\hanna\Anaconda3\lib\site-packages\torch\serialization.py", line 259, in __exit__
    self.file_like.write_end_of_file()
RuntimeError: [enforce fail at ..\caffe2\serialize\inline_container.cc:274] . unexpected pos 41152 vs 41049

**Comment by hn2** [comment]
After reinstalling d3rlpy and pytorch looks like the issue is solved for now.
