### ISSUE TITLE
[BUG] BEAR can't predict.

### ISSUE THREAD

**Issue by masaya611** [takuseno/d3rlpy#142]
I used trained CQL and BEAR to predict next action like the below code.
`action = cql.predict(state)`
`action = bear.predict(state)`

Off course, I built model and loaded parameters. 
However, only in the case of BEAR, I could not predict the next action and got the below error.
```
Traceback (most recent call last):
  File "test_cql.py", line 171, in <module>
    main()
  File "test_cql.py", line 102, in main
    action = choose_action(np.concatenate([state, goal]))
  File "test_cql.py", line 66, in choose_action
    print('action', bear.predict(state))
  File "/home/user/anaconda3/lib/python3.8/site-packages/d3rlpy/algos/base.py", line 150, in predict
    return self._impl.predict_best_action(x)
  File "/home/user/anaconda3/lib/python3.8/site-packages/d3rlpy/torch_utility.py", line 309, in wrapper
    return f(self, *args, **kwargs)
  File "/home/user/anaconda3/lib/python3.8/site-packages/d3rlpy/torch_utility.py", line 299, in wrapper
    return f(self, *tensors, **kwargs)
  File "/home/user/anaconda3/lib/python3.8/site-packages/d3rlpy/algos/torch/base.py", line 50, in predict_best_action
    action = self._predict_best_action(x)
  File "/home/user/anaconda3/lib/python3.8/site-packages/d3rlpy/algos/torch/bear_impl.py", line 322, in _predict_best_action
    flat_values = self._q_func(flat_x, flat_actions, "none")[0]
  File "/home/user/anaconda3/lib/python3.8/site-packages/d3rlpy/models/torch/q_functions/ensemble_q_function.py", line 200, in __call__
    return cast(torch.Tensor, super().__call__(x, action, reduction))
  File "/home/user/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/anaconda3/lib/python3.8/site-packages/d3rlpy/models/torch/q_functions/ensemble_q_function.py", line 194, in forward
    values.append(q_func(x, action).view(1, x.shape[0], 1))
  File "/home/user/anaconda3/lib/python3.8/site-packages/d3rlpy/models/torch/q_functions/base.py", line 59, in __call__
    return self.forward(x, action)
  File "/home/user/anaconda3/lib/python3.8/site-packages/d3rlpy/models/torch/q_functions/mean_q_function.py", line 70, in forward
    return cast(torch.Tensor, self._fc(self._encoder(x, action)))
  File "/home/user/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/anaconda3/lib/python3.8/site-packages/d3rlpy/models/torch/encoders.py", line 402, in forward
    x = torch.cat([x, action], dim=1)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```

**Comment by takuseno** [comment]
@masaya611 Thanks for reporting this issue. I think this is the typical error for the dimension mismatch. Does the `state` have the batch dimension?

**Comment by masaya611** [comment]
Thank you for your reply. Sorry for my misunderstanding.

Now, the size of the state is 1×10 of the numpy array. Dose this have the batch dimension?

**Comment by masaya611** [comment]
It is working!
Thank you for your help.
Why are CQL and BEAR different?

**Comment by takuseno** [comment]
It's good to hear! BEAR is doing something different at prediction, which samples actions from the policy function and chooses the one with the maximum Q-value estimation.
https://github.com/takuseno/d3rlpy/blob/a5932d773dabb801e65702743c76024d0c855cd1/d3rlpy/algos/torch/bear_impl.py#L303
