### ISSUE TITLE
[BUG] CQL Crashing

### ISSUE THREAD

**Issue by emrul** [takuseno/d3rlpy#266]
**Describe the bug**
I'm now comfortable with training using basic DQN and it seems to work fine. I decided to try out CQL instead but it regularly crashes with the following output:

```
Epoch 1/10:  15%|███████████████████▏                                                                       | 750/5000 [14:22<1:21:24,  1.15s/it, loss=3]
Traceback (most recent call last):
  File ".../src/d3rl/train.py", line 82, in <module>
    train()
  File ".../src/d3rl/train.py", line 65, in train
    dqn.fit(train_episodes,
  File ".../d3rlpy/base.py", line 406, in fit
    results = list(
  File ".../d3rlpy/base.py", line 637, in fitter
    loss = self.update(batch)
  File ".../d3rlpy/base.py", line 748, in update
    loss = self._update(batch)
  File ".../d3rlpy/algos/dqn.py", line 129, in _update
    loss = self._impl.update(batch)
  File ".../d3rlpy/torch_utility.py", line 313, in wrapper
    return f(self, *args, **kwargs)
  File ".../d3rlpy/torch_utility.py", line 295, in wrapper
    return f(self, *tensors, **kwargs)
  File ".../d3rlpy/algos/torch/dqn_impl.py", line 108, in update
    loss.backward()
  File ".../site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File ".../site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1024, 30, 102]] is at version 3; expected version 2 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```
(previously it crashed at a different step and suggested I enable `torch.autograd.set_detect_anomaly(True)` which I did to get the trace above. Note: I don't know what the tensor at [1024, 30, 102] is - it isn't a shape I recognise or from my own code.

**To Reproduce**
I'm not sure but my code is taken from examples:
```
    dqn = DiscreteCQL(
        reward_scaler=reward_scaler,
        encoder_factory=xxx,
        n_critics=1,#,2,  # Q function ensemble size
        n_steps=1, # N-step TD backup
        q_func_factory=d3rlpy.models.q_functions.IQNQFunctionFactory(),
        target_update_interval=2000,
        learning_rate=1e-4, #1,
        batch_size=128,
        optim_factory=d3rlpy.models.optimizers.AdamFactory(eps=1e-2 / 64),
        use_gpu=use_gpu
    )

    # initialize neural networks with the given observation shape and action size.
    # this is not necessary when you directly call fit or fit_online method.
    dqn.build_with_dataset(dataset)

    dqn.fit(train_episodes,
            eval_episodes=test_episodes,
            n_steps=50_000,#5_000_000 // 4,
            n_steps_per_epoch=5000,#125000,
            save_interval=1,
            scorers={
                'td_error': td_error_scorer,
                'value_scale': average_value_estimation_scorer,
                'environment': evaluate_scorer
            })

```
Only thing custom is `encoder_factory` and the one I'm using works fine with DQN without any issue.

**Expected behavior**
I would CQL to complete its training loop without crashing.

**Additional context**
It is not clear if I am doing something incorrect or not.

**Comment by takuseno** [comment]
@emrul Hi, thank you for reporting this. Can you give me a minimum example that I can reproduce your issue on my side? On my side, it works fine with your setup.

**Comment by emrul** [comment]
@takuseno - I think the issue may be either in my dataset or in my custom encoder. I will investigate further and re-open if I think it is a library problem. Closing for now.
