### ISSUE TITLE
[BUG] AttributeError from example code in documentation

### ISSUE THREAD

**Issue by pstansell** [takuseno/d3rlpy#33]
**Describe the bug**

There are `AttributeError` from the example code on this page https://d3rlpy.readthedocs.io/en/latest/references/model_based.html

```python
from d3rlpy.dynamics import MOPO
mopo = MOPO()

mopo.horizon = 5
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "/home/ps/miniconda3/envs/d3rlpy/lib/python3.8/site-packages/d3rlpy/base.py", line 151, in __setattr__
#     super().__setattr__(name, value)
# AttributeError: can't set attribute

mopo.n_transitions = 400
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "/home/ps/miniconda3/envs/d3rlpy/lib/python3.8/site-packages/d3rlpy/base.py", line 151, in __setattr__
#     super().__setattr__(name, value)
# AttributeError: can't set attribute
```

**Comment by takuseno** [comment]
@pstansell Thank you for reporting this. The documentation of that page is a bit out-of-the-data now. I'll update the docs.

**Comment by pstansell** [comment]
Thanks (d3rlpy is a superb project!)

**Comment by takuseno** [comment]
Thank you!
