### ISSUE TITLE
[QUESTION] How to customize neural network?

### ISSUE THREAD

**Issue by Lucien-Evans-123** [takuseno/d3rlpy#352]
Greetings,
When I use the code in this link https://d3rlpy.readthedocs.io/en/v2.0.4/tutorials/customize_neural_network.html
I use the customencoder and the factory, and then use it to train discrete cql,
`class CustomEncoder(nn.Module):
    def __init__(self, observation_shape, feature_size):
        super().__init__()
        self.feature_size = feature_size
        self.fc1 = nn.Linear(observation_shape[0], feature_size)
        self.fc2 = nn.Linear(feature_size, feature_size)

    def forward(self, x):
        h = torch.relu(self.fc1(x))
        h = torch.relu(self.fc2(h))
        return h

    # THIS IS IMPORTANT!
    def get_feature_size(self):
        return self.feature_size

class CustomEncoderFactory(d3rlpy.models.encoders.EncoderFactory):
    TYPE = "custom1"  # this is necessary

    def __init__(self, feature_size):
        self.feature_size = feature_size

    def create(self, observation_shape):
        return CustomEncoder(observation_shape, self.feature_size)

    def get_params(self, deep=False):
        return {"feature_size": self.feature_size}`
cql = d3rlpy.algos.DiscreteCQLConfig(batch_size=20,encoder_factory=CustomEncoderFactory(feature_size=64)).create(device='cuda:6')
cql.fit(dataset_offline, n_steps=1000000)

however, the bug told me there is something NotImplemented.

> Traceback (most recent call last):
  File "./Offline_train.py", line 60, in <module>
    cql.fit(dataset_offline, n_steps=1000000)
  File "./python3.8/site-packages/d3rlpy/algos/qlearning/base.py", line 404, in fit
    results = list(
  File "./python3.8/site-packages/d3rlpy/algos/qlearning/base.py", line 497, in fitter
    save_config(self, logger)
  File "./python3.8/site-packages/d3rlpy/base.py", line 137, in save_config
    logger.add_params(config.serialize_to_dict())
  File "./python3.8/site-packages/d3rlpy/serializable_config.py", line 38, in serialize_to_dict
    return self.to_dict()  # type: ignore
  File "./python3.8/site-packages/dataclasses_json/api.py", line 73, in to_dict
    return _asdict(self, encode_json=encode_json)
  File "./python3.8/site-packages/dataclasses_json/core.py", line 385, in _asdict
    return _encode_overrides(dict(result), _user_overrides_or_exts(obj),
  File "./python3.8/site-packages/dataclasses_json/core.py", line 122, in _encode_overrides
    v = encoder(v) if encoder is not None else v
  File "./python3.8/site-packages/d3rlpy/serializable_config.py", line 80, in _encoder
    "params": orig_config.serialize_to_dict(),
  File "./python3.8/site-packages/d3rlpy/serializable_config.py", line 38, in serialize_to_dict
    return self.to_dict()  # type: ignore
  File "./python3.8/site-packages/dataclasses_json/api.py", line 73, in to_dict
    return _asdict(self, encode_json=encode_json)
  File "./python3.8/site-packages/dataclasses_json/core.py", line 385, in _asdict
    return _encode_overrides(dict(result), _user_overrides_or_exts(obj),
  File "./python3.8/site-packages/dataclasses_json/core.py", line 122, in _encode_overrides
    v = encoder(v) if encoder is not None else v
  File "./python3.8/site-packages/d3rlpy/serializable_config.py", line 79, in _encoder
    "type": orig_config.get_type(),
  File "./python3.8/site-packages/d3rlpy/serializable_config.py", line 59, in get_type
    raise NotImplementedError
NotImplementedError

Could you tell how to define the custom network to fix this bug? I am looking forward to your reply. Thanks a lot.

**Comment by takuseno** [comment]
@Lucien-Evans-123 Hi, thank you for the issue. You seem looking at outdated docs. Please take a look at this latest docs.
https://d3rlpy.readthedocs.io/en/v2.2.0/tutorials/customize_neural_network.html

**Comment by takuseno** [comment]
Let me close this issue. Feel free to reopen this if there is any further discussion.

**Comment by Lucien-Evans-123** [comment]
Thank you very much! I really enjoy d3rlpy. I bookmarked this page, so I didn't notice the document updates (hahaha
