### ISSUE TITLE
[BUG]  Error in DDP training of BCQ model

### ISSUE THREAD

**Issue by wenxuhaskell** [takuseno/d3rlpy#367]
**Describe the bug**
Error "AttributeError: 'DistributedDataParallel' object has no attribute 'encoder'" when runing distributed_offline_training.py (using BCQ model instead). This is probably due to the wrapper of DDP and should be similar to #363 that was recently closed.

**To Reproduce**

In distributed_offline_training.py, change CQL to BCQ as below,

...
```
    # setup algorithm
    bcq = d3rlpy.algos.BCQConfig(
        actor_learning_rate=1e-3,
        critic_learning_rate=1e-3,
#        alpha_learning_rate=1e-3,
    ).create(device=device)

```...

and 

```
    # start training
    bcq.fit(
        dataset,
        n_steps=10000,
        n_steps_per_epoch=1000,
        evaluators=evaluators,
        logger_adapter=logger_adapter,
        show_progress=rank == 0,
        enable_ddp=True,
    )

```
Then run the command below,

/> torchrun --nnodes=1 --nproc_per_node=3 --rdzv_id=100 --rdzv_backend=c10d --rdzv_endpoint=localhost:29400 distributed_offline_training.py

**Possible workaround**
In d3rlpy/algos/qlearning/torch/bcq_impl.py,

replace occurrences of 

`self._modules.imitator`

to be 

`self._modules.imitator.module`

This workaround will make it work. Hope this would be helpful for investigating this issue.

**Terminal output**

root@:/home/code/xxx# torchrun --nnodes=1 --nproc_per_node=3 --rdzv_id=100 --rdzv_backend=c10d --rdzv_endpoint=localhost:29400 distributed_offline_training.py
master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Start running on rank=2.
device: cuda:2
Start running on rank=1.
device: cuda:1
Start running on rank=0.
device: cuda:0
2024-01-12 20:43.20 [info     ] Signatures have been automatically determined. action_signature=Signature(dtype=[dtype('float32')], shape=[(1,)]) distributed=DistributedWorkerInfo(rank=2, backend='nccl', world_size=3) observation_signature=Signature(dtype=[dtype('float32')], shape=[(3,)]) reward_signature=Signature(dtype=[dtype('float32')], shape=[(1,)])
2024-01-12 20:43.20 [info     ] Action-space has been automatically determined. action_space=<ActionSpace.CONTINUOUS: 1> distributed=DistributedWorkerInfo(rank=2, backend='nccl', world_size=3)
2024-01-12 20:43.20 [info     ] Action size has been automatically determined. action_size=1 distributed=DistributedWorkerInfo(rank=2, backend='nccl', world_size=3)
2024-01-12 20:43.20 [info     ] Signatures have been automatically determined. action_signature=Signature(dtype=[dtype('float32')], shape=[(1,)]) distributed=DistributedWorkerInfo(rank=1, backend='nccl', world_size=3) observation_signature=Signature(dtype=[dtype('float32')], shape=[(3,)]) reward_signature=Signature(dtype=[dtype('float32')], shape=[(1,)])
2024-01-12 20:43.20 [info     ] Action-space has been automatically determined. action_space=<ActionSpace.CONTINUOUS: 1> distributed=DistributedWorkerInfo(rank=1, backend='nccl', world_size=3)
2024-01-12 20:43.20 [info     ] Action size has been automatically determined. action_size=1 distributed=DistributedWorkerInfo(rank=1, backend='nccl', world_size=3)
2024-01-12 20:43.20 [info     ] Signatures have been automatically determined. action_signature=Signature(dtype=[dtype('float32')], shape=[(1,)]) distributed=DistributedWorkerInfo(rank=0, backend='nccl', world_size=3) observation_signature=Signature(dtype=[dtype('float32')], shape=[(3,)]) reward_signature=Signature(dtype=[dtype('float32')], shape=[(1,)])
2024-01-12 20:43.20 [info     ] Action-space has been automatically determined. action_space=<ActionSpace.CONTINUOUS: 1> distributed=DistributedWorkerInfo(rank=0, backend='nccl', world_size=3)
2024-01-12 20:43.20 [info     ] Action size has been automatically determined. action_size=1 distributed=DistributedWorkerInfo(rank=0, backend='nccl', world_size=3)
2024-01-12 20:43.21 [info     ] dataset info                   dataset_info=DatasetInfo(observation_signature=Signature(dtype=[dtype('float32')], shape=[(3,)]), action_signature=Signature(dtype=[dtype('float32')], shape=[(1,)]), reward_signature=Signature(dtype=[dtype('float32')], shape=[(1,)]), action_space=<ActionSpace.CONTINUOUS: 1>, action_size=1) distributed=DistributedWorkerInfo(rank=0, backend='nccl', world_size=3)
2024-01-12 20:43.21 [info     ] Directory is created at d3rlpy_logs/BCQ_20240112204321 distributed=DistributedWorkerInfo(rank=0, backend='nccl', world_size=3)
2024-01-12 20:43.21 [debug    ] Building models...             distributed=DistributedWorkerInfo(rank=0, backend='nccl', world_size=3)
2024-01-12 20:43.21 [info     ] dataset info                   dataset_info=DatasetInfo(observation_signature=Signature(dtype=[dtype('float32')], shape=[(3,)]), action_signature=Signature(dtype=[dtype('float32')], shape=[(1,)]), reward_signature=Signature(dtype=[dtype('float32')], shape=[(1,)]), action_space=<ActionSpace.CONTINUOUS: 1>, action_size=1) distributed=DistributedWorkerInfo(rank=1, backend='nccl', world_size=3)
2024-01-12 20:43.21 [debug    ] Building models...             distributed=DistributedWorkerInfo(rank=1, backend='nccl', world_size=3)
2024-01-12 20:43.21 [info     ] dataset info                   dataset_info=DatasetInfo(observation_signature=Signature(dtype=[dtype('float32')], shape=[(3,)]), action_signature=Signature(dtype=[dtype('float32')], shape=[(1,)]), reward_signature=Signature(dtype=[dtype('float32')], shape=[(1,)]), action_space=<ActionSpace.CONTINUOUS: 1>, action_size=1) distributed=DistributedWorkerInfo(rank=2, backend='nccl', world_size=3)
2024-01-12 20:43.21 [debug    ] Building models...             distributed=DistributedWorkerInfo(rank=2, backend='nccl', world_size=3)
2024-01-12 20:43.22 [debug    ] Models have been built.        distributed=DistributedWorkerInfo(rank=0, backend='nccl', world_size=3)
2024-01-12 20:43.22 [debug    ] Models have been built.        distributed=DistributedWorkerInfo(rank=1, backend='nccl', world_size=3)
2024-01-12 20:43.22 [debug    ] Models have been built.        distributed=DistributedWorkerInfo(rank=2, backend='nccl', world_size=3)
Epoch 1/10:   0%|                                                                     | 0/1000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/code/xxx/distributed_offline_training.py", line 62, in <module>
    main()
  File "/home/code/xxx/distributed_offline_training.py", line 48, in main
    bcq.fit(
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/d3rlpy/algos/qlearning/base.py", line 400, in fit
    results = list(
              ^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/d3rlpy/algos/qlearning/base.py", line 527, in fitter
    loss = self.update(batch)
           ^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/d3rlpy/algos/qlearning/base.py", line 828, in update
    loss = self._impl.update(torch_batch, self._grad_step)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/d3rlpy/torch_utility.py", line 365, in wrapper
    return f(self, *args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/d3rlpy/algos/qlearning/base.py", line 66, in update
    return self.inner_update(batch, grad_step)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/d3rlpy/algos/qlearning/torch/bcq_impl.py", line 189, in inner_update
    metrics.update(self.update_imitator(batch))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/d3rlpy/algos/qlearning/torch/bcq_impl.py", line 99, in update_imitator
    loss = compute_vae_error(
           ^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/d3rlpy/models/torch/imitators.py", line 192, in compute_vae_error
Epoch 1/10:   0%|                                                                     | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/code/xxx/distributed_offline_training.py", line 62, in <module>
    dist = vae.encoder(x, action)
           ^^^^^^^^^^^
      File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
main()
  File "/home/code/xxx/distributed_offline_training.py", line 48, in main
    bcq.fit(
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/d3rlpy/algos/qlearning/base.py", line 400, in fit
    results = list(
              ^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/d3rlpy/algos/qlearning/base.py", line 527, in fitter
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DistributedDataParallel' object has no attribute 'encoder'    loss = self.update(batch)
           ^^^^^^^^^^^^^^
^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/d3rlpy/algos/qlearning/base.py", line 828, in update
    loss = self._impl.update(torch_batch, self._grad_step)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/d3rlpy/torch_utility.py", line 365, in wrapper
    return f(self, *args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/d3rlpy/algos/qlearning/base.py", line 66, in update
    return self.inner_update(batch, grad_step)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/d3rlpy/algos/qlearning/torch/bcq_impl.py", line 189, in inner_update
    metrics.update(self.update_imitator(batch))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/d3rlpy/algos/qlearning/torch/bcq_impl.py", line 99, in update_imitator
    loss = compute_vae_error(
           ^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/d3rlpy/models/torch/imitators.py", line 192, in compute_vae_error
    dist = vae.encoder(x, action)
           ^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DistributedDataParallel' object has no attribute 'encoder'
Traceback (most recent call last):
  File "/home/code/xxx/distributed_offline_training.py", line 62, in <module>
    main()
  File "/home/code/xxx/distributed_offline_training.py", line 48, in main
    bcq.fit(
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/d3rlpy/algos/qlearning/base.py", line 400, in fit
    results = list(
              ^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/d3rlpy/algos/qlearning/base.py", line 527, in fitter
    loss = self.update(batch)
           ^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/d3rlpy/algos/qlearning/base.py", line 828, in update
    loss = self._impl.update(torch_batch, self._grad_step)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/d3rlpy/torch_utility.py", line 365, in wrapper
    return f(self, *args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/d3rlpy/algos/qlearning/base.py", line 66, in update
    return self.inner_update(batch, grad_step)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/d3rlpy/algos/qlearning/torch/bcq_impl.py", line 189, in inner_update
    metrics.update(self.update_imitator(batch))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/d3rlpy/algos/qlearning/torch/bcq_impl.py", line 99, in update_imitator
    loss = compute_vae_error(
           ^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/d3rlpy/models/torch/imitators.py", line 192, in compute_vae_error
    dist = vae.encoder(x, action)
           ^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DistributedDataParallel' object has no attribute 'encoder'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 910775) of binary: /root/.pyenv/versions/3.11.5/bin/python3.11
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.11.5/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

distributed_offline_training.py FAILED

Failures:
[1]:
  time      : 2024-01-12_20:43:24
  host      : 
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 910776)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-01-12_20:43:24
  host      : 
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 910777)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

Root Cause (first observed failure):
[0]:
  time      : 2024-01-12_20:43:24
  host      : 
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 910775)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by takuseno** [comment]
@wenxuhaskell Thanks for catching this error! I'll look into this to resolve the issue.

**Comment by takuseno** [comment]
@wenxuhaskell I think I've fixed this issue at this latest commit: https://github.com/takuseno/d3rlpy/commit/ee65b1f47371efd0ae3e2aaebc2946cf2f9df56d . If you pull the latest master changes, the issue will be hopefully resolved.

**Comment by wenxuhaskell** [comment]
@takuseno I confirm that the latest master branch fix the reported problem. Please close the thread. Thanks for the quick support!
