### ISSUE TITLE
[Compilation error] Cython.Compiler.Errors.CompileError when running hopper example

### ISSUE THREAD

**Issue by Tengoles** [takuseno/d3rlpy#412]
Python version: 3.9.19
Linux version: Ubuntu 20.04

Steps:
```
Download Linux mujoco 2.1 from https://github.com/openai/mujoco-py?tab=readme-ov-file#install-mujoco and extracted dir to ~/.mujoco/mujoco210

pip install d3rlpy

d3rlpy install d4rl
```

After that run code from example:
```
import d3rlpy

dataset, env = d3rlpy.datasets.get_dataset("hopper-medium-v0")
```

This shows the following error:
```
Compiling /home/enzo/conda_envs/RL/lib/python3.9/site-packages/mujoco_py/cymj.pyx because it changed.
[1/1] Cythonizing /home/enzo/conda_envs/RL/lib/python3.9/site-packages/mujoco_py/cymj.pyx
performance hint: /home/enzo/conda_envs/RL/lib/python3.9/site-packages/mujoco_py/cymj.pyx:67:5: Exception check on 'c_warning_callback' will always require the GIL to be acquired.
Possible solutions:
	1. Declare 'c_warning_callback' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on 'c_warning_callback' to allow an error code to be returned.
performance hint: /home/enzo/conda_envs/RL/lib/python3.9/site-packages/mujoco_py/cymj.pyx:104:5: Exception check on 'c_error_callback' will always require the GIL to be acquired.
Possible solutions:
	1. Declare 'c_error_callback' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on 'c_error_callback' to allow an error code to be returned.

Error compiling Cython file:
------------------------------------------------------------
...
    See c_warning_callback, which is the C wrapper to the user defined function
    '''
    global py_warning_callback
    global mju_user_warning
    py_warning_callback = warn
    mju_user_warning = c_warning_callback
                       ^
------------------------------------------------------------

/home/enzo/conda_envs/RL/lib/python3.9/site-packages/mujoco_py/cymj.pyx:92:23: Cannot assign type 'void (const char *) except * nogil' to 'void (*)(const char *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to the type of 'c_warning_callback'.

Error compiling Cython file:
------------------------------------------------------------
...
    See c_warning_callback, which is the C wrapper to the user defined function
    '''
    global py_error_callback
    global mju_user_error
    py_error_callback = err_callback
    mju_user_error = c_error_callback
                     ^
------------------------------------------------------------

/home/enzo/conda_envs/RL/lib/python3.9/site-packages/mujoco_py/cymj.pyx:127:21: Cannot assign type 'void (const char *) except * nogil' to 'void (*)(const char *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to the type of 'c_error_callback'.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/enzo/conda_envs/RL/lib/python3.9/site-packages/d3rlpy/datasets.py", line 731, in get_dataset
    return get_d4rl(
  File "/home/enzo/conda_envs/RL/lib/python3.9/site-packages/d3rlpy/datasets.py", line 420, in get_d4rl
    import d4rl
  File "/home/enzo/conda_envs/RL/lib/python3.9/site-packages/d4rl/__init__.py", line 14, in <module>
    import d4rl.locomotion
  File "/home/enzo/conda_envs/RL/lib/python3.9/site-packages/d4rl/locomotion/__init__.py", line 2, in <module>
    from d4rl.locomotion import ant
  File "/home/enzo/conda_envs/RL/lib/python3.9/site-packages/d4rl/locomotion/ant.py", line 20, in <module>
    import mujoco_py
  File "/home/enzo/conda_envs/RL/lib/python3.9/site-packages/mujoco_py/__init__.py", line 2, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/home/enzo/conda_envs/RL/lib/python3.9/site-packages/mujoco_py/builder.py", line 504, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "/home/enzo/conda_envs/RL/lib/python3.9/site-packages/mujoco_py/builder.py", line 110, in load_cython_ext
    cext_so_path = builder.build()
  File "/home/enzo/conda_envs/RL/lib/python3.9/site-packages/mujoco_py/builder.py", line 226, in build
    built_so_file_path = self._build_impl()
  File "/home/enzo/conda_envs/RL/lib/python3.9/site-packages/mujoco_py/builder.py", line 296, in _build_impl
    so_file_path = super()._build_impl()
  File "/home/enzo/conda_envs/RL/lib/python3.9/site-packages/mujoco_py/builder.py", line 239, in _build_impl
    dist.ext_modules = cythonize([self.extension])
  File "/home/enzo/conda_envs/RL/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
    cythonize_one(*args)
  File "/home/enzo/conda_envs/RL/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: /home/enzo/conda_envs/RL/lib/python3.9/site-packages/mujoco_py/cymj.pyx
```

**Comment by takuseno** [comment]
@Tengoles Hi, thank you for the issue. This is MuJoCo's issue rather than d3rlpy's. Please report this error to https://github.com/google-deepmind/mujoco . Let me close this issue.
