### ISSUE TITLE
[BUG] d3rlpy install minari

### ISSUE THREAD

**Issue by kikido16** [takuseno/d3rlpy#433]
**Describe the bug**
I am trying to use d3rlpy==2.6.0 and the kitchen dataset from d4rl. I have checked the issue #358 and use `d3rlpy install minari` to install minari. But there are still some bugs to use the kitchen dataset.
 
**To Reproduce**
```
from d3rlpy.datasets import get_minari
dataset, env=get_minari('kitchen-complete-v1')
```
And it report bugs like this:
```
  File "/d4rl/d3rlpy_test/d3rlpy_demo.py", line 21, in <module>
    import minari
  File "/anaconda3/envs/d3rlpy/lib/python3.8/site-packages/minari/__init__.py", line 10, in <module>
    from minari.utils import (
  File "/anaconda3/envs/d3rlpy/lib/python3.8/site-packages/minari/utils.py", line 15, in <module>
    from gymnasium.wrappers.record_episode_statistics import RecordEpisodeStatistics
ModuleNotFoundError: No module named 'gymnasium.wrappers.record_episode_statistics'
```
Then I checked the docs for gymnasium and found that `RecordEpisodeStatistics` is now in `gymnasium.wrappers.vector`.
Though the above bugs can be fixed by the above procedures, there is still a new bug, which is shown as follows:
```
  File "/anaconda3/envs/d3rlpy/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 189, in from_json
    env_spec = EnvSpec(**parsed_env_spec)
TypeError: __init__() got an unexpected keyword argument 'autoreset'

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/d4rl/d3rlpy_test/d3rlpy_demo.py", line 79, in <module>
    main()
  File "/d4rl/d3rlpy_test/d3rlpy_demo.py", line 26, in main
    dataset, env=get_minari('kitchen-complete-v1')
  File "/anaconda3/envs/d3rlpy/lib/python3.8/site-packages/d3rlpy/datasets.py", line 495, in get_minari
    _dataset = minari.load_dataset(env_name, download=True)
  File "/anaconda3/envs/d3rlpy/lib/python3.8/site-packages/minari/storage/local.py", line 39, in load_dataset
    return MinariDataset(data_path)
  File "/anaconda3/envs/d3rlpy/lib/python3.8/site-packages/minari/dataset/minari_dataset.py", line 137, in __init__
    self._data = MinariStorage(data)
  File "/anaconda3/envs/d3rlpy/lib/python3.8/site-packages/minari/dataset/minari_storage.py", line 34, in __init__
    self._env_spec = EnvSpec.from_json(f.attrs["env_spec"])
  File "/anaconda3/envs/d3rlpy/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 192, in from_json
    raise ValueError(
ValueError: An issue occurred when trying to make {'id': 'FrankaKitchen-v1', 'entry_point': 'gymnasium_robotics.envs.franka_kitchen:KitchenEnv', 'reward_threshold': None, 'nondeterministic': False, 'max_episode_steps': 280, 'order_enforce': True, 'autoreset': False, 'disable_env_checker': False, 'apply_api_compatibility': False, 'kwargs': {'remove_task_when_completed': False, 'terminate_on_tasks_completed': False, 'tasks_to_complete': ['microwave', 'kettle', 'light switch', 'slide cabinet']}, 'vector_entry_point': None} an EnvSpec
```
It seems that `d3rlpy install minari` will  install `gymnasium==1.0.0`, but in `gymnasium==1.0.0` , `autoreset` was moved according to the change logs.
I also tried to degrade the gymnasium version, but after degradation, it will report the error:  `ImportError: minari is not installed.`

**Comment by kikido16** [comment]
I have solved this problem by manually updating the Minari version to the latest release (v0.5.1). I will close this issue now.

**Comment by kikido16** [comment]
I have solved this problem by manually updating the Minari version to the latest release (v0.5.1). I will close this issue now.

**Comment by takuseno** [comment]
Sorry for the late response. I have made a change to resolve the issue at this commit https://github.com/takuseno/d3rlpy/commit/7be4f673129bca6c9c7a1a84f750a6a8aa4b52b4 . If you install the latest d3rlpy from the source code, the issue should be fixed.

**Comment by kikido16** [comment]
> Sorry for the late response. I have made a change to resolve the issue at this commit [7be4f67](https://github.com/takuseno/d3rlpy/commit/7be4f673129bca6c9c7a1a84f750a6a8aa4b52b4) . If you install the latest d3rlpy from the source code, the issue should be fixed.

Thank you for your time and efforts!
